jobs:
  qa:
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v6'
      - name: 'Install dependencies (Yarn)'
        run: |
          yarn
          brew install swift-format
          python3 -m venv .venv
          . .venv/bin/activate
          pip install cmakelang pyyaml
      - name: 'Check formatting'
        run: '. .venv/bin/activate && yarn check-formatting'
      - name: 'Check spelling'
        run: 'yarn check-spelling'
name: 'QA'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
